name: Larave-Inventory Test

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  laravel-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php: [8.0, 7.4]
        laravel: [8.*]
        dependency-vesrion: [prefer-lowest, prefer-stable]
        include:
          -   laravel: 8.*
              testbench: 6.*

    name: PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
        
      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v2
        with:
         path: vendor
         key: ${{ matrix.os }}-php-${{ hashFiles('**/composer.lock') }}
         restore-keys: |
           ${{ matrix.os }}-php-
           
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none
          
      -   name: Install dependencies
          run: composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
               composer update --prefer-dist --no-interaction --no-suggest

      -   name: Execute Tests
          run: vendor/bin/phpunit
